#!/bin/bash

# Tests infinite inputs generated by gen. 
# It compares the output of a.cpp and brute.cpp and 
# stops if there's any difference. 

g++ -std=c++17 gen.cpp -o gen
g++ -std=c++17 a.cpp -o a
g++ -std=c++17 brute.cpp -o brute

for((i=1;;i++)); do
	echo $i
	./gen $i > in
  time ./a < in > o1
	./brute < in > o2
	diff <(./a < in) <(./brute < in) || break
done

cat in
echo 'mine'
cat o1
echo 'not mine'
cat o2
#sed -i 's/\r$//' filename  ----- remover \r do txt
